### ISSUE TITLE
Cailiri (body) renders a strange not recognized letter when using bold typeface.

### ISSUE THREAD

**Issue by hrachia** [MicrosoftDocs/typography-issues#813]
When typing in Armenian, Calibri renders a strange non-Armenian letter instead of **և**. It only happens with Calibri (body) bold typeface, the thinner Calibri (header) doesn't have that problem. 

I sent this feedback to Microsoft through the Insider channel six months ago but that bug hasn't been fixed yet.

![calibri](https://user-images.githubusercontent.com/88577422/128594941-7cc04657-751b-4b5c-a245-9cdb3aedb9ad.png)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 72c7cadc-6eb0-3a3a-b325-de0aa45e4852
* Version Independent ID: 65e39cbd-0456-87d9-2446-d46dd39dce71
* Content: [Calibri font family - Typography](https://docs.microsoft.com/en-us/typography/font-list/calibri)
* Content Source: [typographydocs/font-list/calibri.md](https://github.com/MicrosoftDocs/typography/blob/live/typographydocs/font-list/calibri.md)
* Product: **typography**
* GitHub Login: @alib-ms
* Microsoft Alias: **alib**

**Comment by kenmcd** [comment]
> When typing in Armenian, Calibri renders a strange non-Armenian letter instead of **և**. It only happens with Calibri (body) bold typeface, the thinner Calibri (header) doesn't have that problem.

Calibri does not have that character in the fonts, and does not support Armenian.
So what you are dealing with is a fallback to a different font(s).

You can see which actual font is being substituted by exporting to PDF and then using your PDF reader/editor to check the actual font used on that text.

**Comment by tiroj** [comment]
> Calibri does not have that character in the fonts, and does not support Armenian.

Recent versions of Calibri that ship with Windows _do_ include Armenian support. Older versions that may ship with some versions of Office or older versions of Windows do not.

I’ve not had a chance to investigate this issue yet.

**Comment by hrachia** [comment]
Please look into that pretty annoying problem John, because that frequently used letter makes the entire font useless in Armenian.


Many thanks,

Hrachia



Sent from my Galaxy



-------- Original message --------
From: John Hudson ***@***.***>
Date: 09/08/2021 04:29 (GMT+04:00)
To: MicrosoftDocs/typography-issues ***@***.***>
Cc: hrachia ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/typography-issues] Cailiri (body) renders a strange not recognized letter when using bold typeface. (#813)


Calibri does not have that character in the fonts, and does not support Armenian.

Recent versions of Calibri that ship with Windows do include Armenian support. Older versions that may ship with some versions of Office or older versions of Windows do not.

I’ve not had a chance to investigate this issue yet.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Ftypography-issues%2Fissues%2F813%23issuecomment-894882492&data=04%7C01%7C%7C640590322cbb40f414d208d95accc564%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640657795924622%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=X%2BSHuyKQUmuxhF3wOEpgsgSjkCpihdjIBEJH6TAqNeg%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVDZLDSYPDBW4YSCHSVHVXDT34OPBANCNFSM5BXGVIUA&data=04%7C01%7C%7C640590322cbb40f414d208d95accc564%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640657795934608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=b1TRMvfNn2E%2B0je9r3sJR3JiIlg49cUL519%2BswaQ33Q%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C640590322cbb40f414d208d95accc564%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640657795934608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ySEryrdYe1xhYtW4qx6rDKlGcMOayngqp%2BIGWMXT6TQ%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7C640590322cbb40f414d208d95accc564%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637640657795934608%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=flABNCKRBVVOc3yrRAxpwdzYxzDnSqz3naCpVu3UMa0%3D&reserved=0>.

**Comment by LornaSIL** [comment]
There is definitely something wrong with the font for Armenian. Regular and Bold have characters encoded at U+058B and U+058C (and nothing is encoded there in Unicode) with different glyphs. The glyph in Bold that is desired is at U+058B rather than U+0587 as it should be.

**Comment by hrachia** [comment]
Many thanks Lorna, the issue has been around since the introduction of the new font, hope it won't take long to fix.

With best wishes

Hrachia



Sent from my Galaxy



-------- Original message --------
From: Lorna Evans ***@***.***>
Date: 09/08/2021 18:29 (GMT+04:00)
To: MicrosoftDocs/typography-issues ***@***.***>
Cc: hrachia ***@***.***>, Author ***@***.***>
Subject: Re: [MicrosoftDocs/typography-issues] Cailiri (body) renders a strange not recognized letter when using bold typeface. (#813)


There is definitely something wrong with the font for Armenian. Regular and Bold have characters encoded at U+058B and U+058C (and nothing is encoded there in Unicode) with different glyphs. The glyph in Bold that is desired is at U+058B rather than U+0587 as it should be.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Ftypography-issues%2Fissues%2F813%23issuecomment-895272302&data=04%7C01%7C%7Cf392decc96f64c0778b008d95b4212f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641161605166096%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z5HTkax0FVfjw6lcXV2ytOhfGpTXaJ%2FvK7IKTtdc%2Ba0%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAVDZLDV7SNSXE3SJS5XCWJTT37Q37ANCNFSM5BXGVIUA&data=04%7C01%7C%7Cf392decc96f64c0778b008d95b4212f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641161605176087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=18J3J5hX1RR%2BfVwd5bfp35nScYUxLMWonq7fLbBJ7HI%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7Cf392decc96f64c0778b008d95b4212f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641161605176087%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iUqLWwG%2F%2Fbk5AAWsBqI9MjfRqtFiZfCGaqr6Pddnu04%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7C%7Cf392decc96f64c0778b008d95b4212f8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637641161605186083%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=UPfS%2FBo1jdnCN32pyDx%2BKGv0KJxBoct3tMtvPEWB%2BGo%3D&reserved=0>.

**Comment by alib-ms** [comment]
Thank you for reporting the issue. We have added Arabic, Hebrew, Armenian and Georgian support in the Calibri font family. I will have this fixed.

**Comment by alib-ms** [comment]
It looks like Calibri Bold had three Armenian characters incorrectly encoded.
և, ֋, ֌

Issue has been fixed. Updated fonts checked-in.

**Comment by hrachia** [comment]
Thank you very much! When do you think it will be possible to download the corrected fonts?
________________________________

**Comment by alib-ms** [comment]
I have notified the Office team. We are hoping the updated fonts will be shipped sometime in October-November time frame.

**Comment by hrachia** [comment]
Hello,

I have used the Feedback Hub highlighting this problem many times for more than two years now, with no progress and no reply whatsoever, so, in a sense, the Feedback Hub proved just a waste of time. Unfortunately, the issue persists, even with updated Windows 11 and it seems that nobody in Microsoft realizes that that frequent Armenian letter renders Calibri - the default Office font - useless for Armenians..


Many thanks

Hrachia

**Comment by hrachia** [comment]
Dear Ali

Thank you, I installed the 22H2 yesterday, and the long-awaited fix was there.


With best wishes

Hrachia

From: Hrachia Kazhoyan
Sent: Friday, 11 March 2022 16:35
To: MicrosoftDocs/typography-issues ***@***.***>; MicrosoftDocs/typography-issues ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [MicrosoftDocs/typography-issues] Cailiri (body) renders a strange not recognized letter when using bold typeface. (#813)

Hello,

I have used the Feedback Hub highlighting this problem many times for more than two years now, with no progress and no reply whatsoever, so, in a sense, the Feedback Hub proved just a waste of time. Unfortunately, the issue persists, even with updated Windows 11 and it seems that nobody in Microsoft realizes that that frequent Armenian letter renders Calibri - the default Office font - useless for Armenians..


Many thanks

Hrachia

**Comment by alib-ms** [comment]
Thank you for reporting the issue and confirming the fix. Sorry that it took so long. I will report your concerns to the Feedback Hub team. 

Thanks,
Ali
